name: Python Code Analysis

on:
  push:
    branches: [ali_branch]
  pull_request:
    branches: [main]

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Install pylint
        run: pip install pylint

      - name: Run Pylint
        run: pylint --disable=all $(git ls-files '*.py')
        
      - name: Install black
        run: pip install black
        
      - name: Run Black
        run: black .

      - name: Set up CodeQL
        uses: github/codeql-action@v2
        with:
          # Path to the CodeQL database
          database-path: ${{github.workspace}}/codeql_database

      - name: Build and test code
        run: |
          # Build and test code here

      - name: Upload results
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to the SARIF file containing the results of the CodeQL analysis
          sarif_file: codeql_database/codeql.sarif
